### ISSUE TITLE
can't import lazy_import 

### ISSUE THREAD

**Issue by jessica-anyen** [open-mmlab/mmskeleton#256]
when i run 'python mmskl.py pose_demo' i got  the error message below:
**'ModuleNotFoundError: No module named 'lazy_import'**
for that i try 'pip install lazy-import', then i get the error message: 
'**UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 621: ordinal not in range(128)**'

Does someone have the same problem? Is there any way to replace the lazy-import?

我在執行'python mmskl.py pose_demo'指令的時候，錯誤訊息為:
'ModuleNotFoundError: No module named 'lazy_import'
執行pip安裝，會出現錯誤訊息:
'UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 621: ordinal not in range(128)'
請問遇到這個問題應該如何解決? 是否有不使用lazy-import的方法?

**Comment by yysijie** [comment]
@jessica-anyen, fixed, thanks!

**Comment by GaahoLeung** [comment]
there is also a problem like:
'UnicodeDecodeError: 'gbk' codec can't decode byte 0xa5 in position 623: illegal multibyte sequence'

**Comment by liunian199** [comment]
how do you fix it？

**Comment by GaahoLeung** [comment]
https://blog.csdn.net/u014437141/article/details/106161018
试试？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"liunian199"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月21日(星期四) 晚上8:40
收件人:&nbsp;"open-mmlab/mmskeleton"<mmskeleton@noreply.github.com&gt;;
抄送:&nbsp;"411973089"<411973089@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [open-mmlab/mmskeleton] can't import lazy_import  (#256)





 
how do you fix it？

**Comment by pranavgundewar** [comment]
I am still facing this issue

**Comment by khm159** [comment]
this might be happening because "lazy_import" module is not installed 
so pip try to install "lazy_import" module in your computer 

it's try to run "setup.py" in "lazy_import" module's pakage
in setup.py there is code line 
    
    with open('README.rst') as infile:
    readme = infile.read()

if your os's encoding is different to pakage's environment. then error is occur.

**Try below. in my case. It works.**

    **git clone https://github.com/mnmelo/lazy_import
    cd lazy_import**

    and open setup.py using any editor and change this line

    **with open('README.rst') as infile:
    readme = infile.read()**

to

    **with open('README.rst', encoding='your encoding') as infile:
    readme = infile.read()**

and pip install . (in lazy_import directory)

in my case
your encoding = cp949

**Comment by khm159** [comment]
> I am still facing this issue

check my reply :)

**Comment by vasanth4224** [comment]
this might be happening because "lazy_import" module is not installed
so pip try to install "lazy_import" module in your computer

it's try to run "setup.py" in "lazy_import" module's pakage
in setup.py there is code line

with open('README.rst') as infile:
readme = infile.read()
if your os's encoding is different to pakage's environment. then error is occur.

Try below. in my case. It works.

git clone https://github.com/mnmelo/lazy_import
cd lazy_import

and open setup.py using any editor and change this line

with open('README.rst') as infile:
readme = infile.read()
to

with open('README.rst', encoding='your encoding') as infile:
readme = infile.read()
and pip install . (in lazy_import directory)

in my case
your encoding = 'utf-8'

It is working... Thank you

**Comment by trotsky1997** [comment]
just clone this repo and install.
```
git clone https://github.com/trotsky1997/lazy_import.git
cd lazy_import
pip install .
```
